version: "3"

services:
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://user:pa55word@mongo:27017/

